### ISSUE TITLE
keithley_driver.py: TypeError for while status > 0

### ISSUE THREAD

**Issue by quaeritis** [OE-FET/keithley2600#7] opened 2018-11-08 15:05 UTC
I have problems with the type of variable status since the last changes:
```
$ keithleygui
Could not connect to Keithley at GPIB0::26::INSTR.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\keithleygui-0.1.0-py3.6.egg\keithleygui\main.py", line 658, in run
    self.params['tInt'], self.params['delay'], self.params['pulsed']
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\keithley2600-0.2.0-py3.6.egg\keithley2600\keithley_driver.py", line 928, in transferMeasurement
    smu_gate, smu_drain, sweeplist_gate, sweeplist_drain, tInt, delay, pulsed
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\keithley2600-0.2.0-py3.6.egg\keithley2600\keithley_driver.py", line 869, in voltageSweepDualSMU
    while status > 0:  # while loop that runs until the sweep ends
TypeError: '>' not supported between instances of 'NoneType' and 'int'
QObject::~QObject: Timers cannot be stopped from another thread
```
Did they also occur with you @SamSchott?

**Comment by SamSchott** [comment] 2018-11-08 16:24
Just, checked, yes it does. It's a new bug, probably from changing `_lock` to an instance variable, resulting in queries sometimes not returning a response (or the response from a previous query). 

I have moved `_lock` back to a class variable now, this should hopefully fix it.

**Comment by quaeritis** [comment] 2018-11-08 16:42
fix:  67ec26e
OK thanks.
Then I will close this here as soon as I have tested it.

**Comment by SamSchott** [comment] 2018-11-08 19:45
@quaeritis, I have pushed a few more bug fixes regarding my try of implementing a "singleton" class. Now, trying to create a second instance with an already existing Keithley address will return the old instance instead.

**Comment by SamSchott** [comment] 2018-11-09 15:57
I cannot seem to reproduce this here. Does a restart of the Keithley and the Python console help by any chance? If not, could you run the following in the python console before trying a sweep, and post the output?

```Python
import logging
from keithley2600.keithley_driver import logger
ch = logging.StreamHandler()
logger.addHandler(ch)
logger.setLevel(logging.DEBUG)
```

The driver will then print all communication with the Keithley during a sweep to the console.

**Comment by quaeritis** [comment] 2018-11-13 13:29
Hi @SamSchott,

I finally had time to test here the result:

```python
import logging
from keithley2600.keithley_driver import logger
ch = logging.StreamHandler()
logger.addHandler(ch)
logger.setLevel(logging.DEBUG)

from keithley2600 import Keithley2600
k = Keithley2600('GPIB0::26::INSTR', r'C:\Program Files (x86)\IVI Foundation\VISA\WinNT\agvisa\agbin\visa32.dll')
data = k.readBuffer('smua.nvbuffer1')
k.clearBuffer(k.smua) # clears buffer of k.smua

k.voltageSweepSingleSMU(smu=k.smua, smu_sweeplist=list(range(0, 5)),
                            tInt=0.1, delay=-1, pulsed=False)

```

````
$ python test2.py >> log.txt
Connected to Keithley at GPIB0::26::INSTR.
Creating new instance with address GPIB0::26::INSTR.
print(smua.nvbuffer1.n)
smua.nvbuffer1.clear()
smua.nvbuffer1.clearcache()
result = smua.nvbuffer1.clear()
print(result)
result = smua.nvbuffer2.clear()
print(result)
result = smua.nvbuffer1.clearcache()
print(result)
result = smua.nvbuffer2.clearcache()
print(result)
result = smua.trigger.source.listv({0, 1, 2, 3, 4})
print(result)
print(smua.ENABLE)
smua.trigger.source.action = 1.0
print(localnode.linefreq)
smua.measure.nplc = 5.0
smua.measure.delay = -1
print(smua.AUTORANGE_ON)
smua.measure.autorangei = 1.0
print(smua.OUTPUT_DCVOLTS)
smua.source.func = 1.0
result = smua.nvbuffer1.clear()
print(result)
result = smua.nvbuffer2.clear()
print(result)
result = smua.nvbuffer1.clearcache()
print(result)
result = smua.nvbuffer2.clearcache()
print(result)
print(display.MEASURE_DCAMPS)
display.smua.measure.func = 0.0
print(display.MEASURE_DCAMPS)
display.smub.measure.func = 0.0
smua.trigger.count = 5
print(smua.ENABLE)
smua.trigger.measure.action = 1.0
result = smua.trigger.measure.iv(smua.nvbuffer1, smua.nvbuffer2)
print(result)
print(smua.trigger.SOURCE_COMPLETE_EVENT_ID)
smua.trigger.measure.stimulus = 46.0
smua.trigger.endpulse.action = 1
smua.trigger.endsweep.action = 1
print(trigger.EVENT_ID)
smua.trigger.arm.stimulus = 29.0
trigger.blender[1].orenable = true
print(smua.trigger.ARMED_EVENT_ID)
trigger.blender[1].stimulus[1] = 48.0
print(smua.trigger.PULSE_COMPLETE_EVENT_ID)
trigger.blender[1].stimulus[2] = 47.0
print(trigger.blender[1].EVENT_ID)
smua.trigger.source.stimulus = 57.0
trigger.blender[2].orenable = true
print(smua.trigger.MEASURE_COMPLETE_EVENT_ID)
trigger.blender[2].stimulus[1] = 45.0
print(trigger.blender[2].EVENT_ID)
smua.trigger.endpulse.stimulus = 58.0
print(smua.OUTPUT_ON)
smua.source.output = 1.0
result = smua.trigger.initiate()
print(result)
*trg
print(status.operation.sweeping.condition)
print(status.operation.sweeping.condition)
print(status.operation.sweeping.condition)
print(status.operation.sweeping.condition)
....
print(status.operation.sweeping.condition)
print(status.operation.sweeping.condition)
print(status.operation.sweeping.condition)
print(smua.nvbuffer2.n)
print(smua.nvbuffer2[1])
print(smua.nvbuffer2[2])
print(smua.nvbuffer2[3])
print(smua.nvbuffer2[4])
print(smua.nvbuffer2[5])
smua.nvbuffer2.clear()
smua.nvbuffer2.clearcache()
print(smua.nvbuffer1.n)
print(smua.nvbuffer1[1])
print(smua.nvbuffer1[2])
print(smua.nvbuffer1[3])
print(smua.nvbuffer1[4])
print(smua.nvbuffer1[5])
smua.nvbuffer1.clear()
smua.nvbuffer1.clearcache()
result = smua.nvbuffer1.clear()
print(result)
result = smua.nvbuffer2.clear()
print(result)
result = smua.nvbuffer1.clearcache()
print(result)
result = smua.nvbuffer2.clearcache()
print(result)
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\pyvisa\resources\resource.py", line 108, in __del__
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\pyvisa\resources\resource.py", line 243, in close
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\pyvisa\resources\resource.py", line 235, in before_close
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\pyvisa\resources\resource.py", line 252, in __switch_events_off
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\pyvisa\resources\resource.py", line 309, in disable_event
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\pyvisa\ctwrapper\functions.py", line 410, in disable_event
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 188, in _return_handler
pyvisa.errors.VisaIOError: VI_ERROR_INV_OBJECT (-1073807346): The given session or object reference is invalid.

````

**Comment by SamSchott** [comment] 2018-11-13 17:13
@quaeritis, I am puzzled by this error. The commands sent by the driver seem fine and your code runs without problems our Linux machine (with both the NI-VISA and '@py' backends over ethernet). Does the Keithley actually carry out the sweep? I find it strange that the connection is lost only at the end of the script, just before `k.voltageSweepSingleSMU(...)` returns.

This seems to be a backend specific problem, possibly related to GPIB. I also noticed that you are using a visa library from Agilent. Could you try installing NI-VISA from [here](http://www.ni.com/download/ni-visa-18.0/7597/en/) instead and see if the problem persists?

I have also updated the driver so that one can pass VISA keyword arguments to the connection, such as `baud_date=9600`, this may help in some cases.

Unfortunately there is currently no debug mode for the keithleygui, only for the driver. But your problem seems either driver or backend related. You can get a similar output by adding

```Python
import logging
logger = logging.getLogger('keithley2600')
logger.addHandler(logging.StreamHandler())
logger.setLevel(logging.DEBUG)
```

to the `run()` function of keithleygui. You can get the pyvisa debug output from `logger = logging.getLogger('pyivsa')` but it will be very verbose.

**Comment by quaeritis** [comment] 2018-11-13 21:31
@SamSchott, I was also pretty sure that this is a backend specific problem. Unfortunately we use here a USB to GPIB adapter which I only brought to work with the Agilent library. To be honest, pyvisa-py or NI-VISA would be better.

I will report back if I have time to test.
(Must be quieter always in the clean room which is a bit annoying :-))

**Comment by quaeritis** [comment] 2018-11-16 10:20
Hi @SamSchott,

 I think I found the problem. The error -363 (Input buffer overrun) is caused by smub.trigger.source.listv if a large list is passed to them, the keithley does not seem to be able to process them.

I've had such a problem before, the solution was to send the list values one by one. Such a solution would be rather difficult to implement with the driver or?

**Comment by SamSchott** [comment] 2018-11-16 14:43
I was not aware of any limits to the list length. Passing lists with 1000 elements works fine for our Keithley 2612b and should not be a limitation of the `smuX.trigger.source.listv` function. Did the previous version of the driver, which used `smuX.trigger.source.linearv` to create a linear sweep list, work for you? If yes, it seems that your Keithley or your Visa library do not like receiving or sending long commands.

We could either revert to supporting linear sweeps only through `smuX.trigger.source.linearv`, which would be a shame, find a way to increase the input buffer size, or sent values individually and construct the list on the Keithley.

Unfortunately, the driver does not currently support creating any new Keithley objects but only using existing ones. One could dynamically add created keithley objects to `driver_doc.CONSTANTS`, `driver_doc.PROPERTRIES`, etc, but would need to prevent conflicts with instance attributes of the driver itself.

Alternatively, to construct lists on the Keithley itself, you would need to revert to manual `_write` commands, like so:

```Python
def _create_long_list(self, name, list):
    self._write('%s = {}' % name)
    i = 1
    for val in list:
        self._write('%s[%s] = %s' % (name, i, val))

_create_long_list('tmp_list', smu_sweep_list)
self.smuX.trigger.source.listv('tmp_list')
```

I leave this for you to implement and test. Ideally, one would use the regular method for short lists and the above as a fallback for lists exceeding the input buffer length.

**Comment by SamSchott** [comment] 2018-11-21 10:40
Closing, as the original TypeError was fixed.

I pushed a workaround that reverts to using `trigger.source.linearv` if an evenly spaced list or array is passed (will be the case for all sweeps from the GUI).

Please open a new bug if the input buffer overrun persists.

**Closed** 2018-11-21 10:42 UTC
Labels: bug, fixed
